protocol_mapping:
  bedbuncher: bedbuncher

pipelines:
  bedbuncher:
    name: bedbuncher
    path: bedbuncher.py
    looper_args: True
    arguments:
      "--JSON-query-path": JSONquery_path
      "--bedset-name": bedset_name
      "--output-folder": output_folder_path
    optional_arguments:
      "--bbconfig": bbconfig_path
    resources:
      default: 
        file_size: "0"
        cores: "1"
        mem: "12000"
        time: "00-18:00:00"
    






