protocol_mapping:
  bedbuncher: bedbuncher

pipelines:
  bedbuncher:
    name: BEDBUNCHER
    path: pipelines/bedbuncher.py
    command_template: >
      {pipeline.path}
      --JSON-query-path {sample.JSONquery_path}
      --bedset-name {sample.bedset_name}
      {% if sample.bbconfig_path is defined %} --bedbase-config {sample.bbconfig_path} {% endif %}
    compute:
      size_dependent_variables: resources.tsv
