protocol_mapping:
  bedbuncher: bedbuncher

pipelines:
  bedbuncher:
    name: bedbuncher
    path: bedbuncher_ESlowclient.py
    looper_args: True
    arguments:
      "--JSONquery": JSONquery_path
      "--bedset-name": bedset_name
      "-output_folder": output_folder_path
      "--bbconfig-path": bbconfig_path
    resources:
      default: 
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "00-18:00:00"
    






